vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_product_image:
            uri_prefix: /images/product_image
            upload_destination: '%kernel.project_dir%/public/images/product_image'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

